import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class DepartmentService {
  constructor() {}

  getDepartmentList() {
    return [
      {
        _id: 'dp0001',
        email: 'ctsv@uel.edu.vn',
        logoUrl: 'dp0001.png',
        name: 'Phòng Tuyển sinh & Công tác sinh viên',
        newsLink: 'https://ctsv.uel.edu.vn/thong-bao-chung-5',
        notiLink: 'https://ctsv.uel.edu.vn/tin-tuc-ctsv',
        page: 'https://www.facebook.com/UELDASA',
        phone: ['(+8428)47244555', '(+8428)47244535'],
        room: ['A.007', 'A.001'],
        star: true,
        website: 'ctsv.uel.edu.vn',
      },
      {
        _id: 'dp0002',
        email: 'phongdaotao@uel.edu.vn',
        logoUrl: 'dp0002.png',
        name: 'Phòng Đào tạo',
        newsLink: 'https://pdt.uel.edu.vn/tin-tuc-5',
        notiLink: 'https://pdt.uel.edu.vn/dai-hoc-chinh-quy-2819',
        page: 'https://www.facebook.com/UELDASA',
        phone: ['(028)37244551', 'Fax: 37244500'],
        room: ['A008'],
        star: true,
        website: 'pdt.uel.edu.vn',
      },
      {
        _id: 'dp0003',
        email: 'cntt@uel.edu.vn',
        logoUrl: 'dp0003.png',
        name: 'Phòng công nghệ thông tin',
        newsLink: 'https://cntt.uel.edu.vn/tin-tuc-4',
        notiLink: 'https://cntt.uel.edu.vn/thong-bao2-35',
        page: 'https://www.facebook.com/cntt.uel.edu.vn/',
        phone: ['(028) 37244555 (Ext 6621 - 6622)', 'Fax: (08) 37244500'],
        room: ['A.513'],
        star: true,
        website: 'ctsv.uel.edu.vn',
      },
      {
        _id: 'dp0004',
        email: 'doanhoi@uel.edu.vn ',
        logoUrl: 'dp0004.png',
        name: 'Văn phòng Đoàn hội',
        newsLink: 'https://youth.uel.edu.vn/tin-tuc-hoat-dong-760',
        notiLink: 'https://youth.uel.edu.vn/hoc-tap-nckh-2',
        page: 'https://www.facebook.com/youth.uel/',
        phone: ['083 7244555(Ext 6391)'],
        room: ['A.210'],
        star: false,
        website: 'youth.uel.edu.vn',
      },
      {
        _id: 'dp0005',
        email: 'khoahttt@uel.edu.vn',
        logoUrl: 'dp0005.png',
        name: 'Khoa Hệ thống thông tin',
        newsLink: 'https://is.uel.edu.vn/tin-tuc-34',
        notiLink: 'https://is.uel.edu.vn/thong-bao2-3',
        page: 'https://www.facebook.com/khoahttt.uel',
        phone: ['0837244555 (6491)'],
        room: ['B2.403'],
        star: true,
        website: 'is.uel.edu.vn',
      },
      {
        _id: 'dp0006',
        email: 'khoaktdn@uel.edu.vn',
        logoUrl: 'dp0006.png',
        name: 'Khoa Kinh tế đối ngoại',
        newsLink: 'https://ktdn.uel.edu.vn/hoat-dong-sinh-vien-1165',
        notiLink: 'https://ktdn.uel.edu.vn/dao-tao-nghien-cuu',
        page: 'https://www.facebook.com/',
        phone: [' (+84) 8 3724 4555', 'Fax: (+84) 8 3724 4500'],
        room: ['B2.606'],
        star: false,
        website: 'ktdn.uel.edu.vn',
      },
      {
        _id: 'dp0007',
        email: 'khoaluat@uel.edu.vn',
        logoUrl: 'dp0007.png',
        name: 'Khoa Luật',
        newsLink: 'https://law.uel.edu.vn/tin-tuc-32',
        notiLink: 'https://law.uel.edu.vn/thong-bao2-59',
        page: 'https://www.facebook.com/',
        phone: ['(08) 37244555 (6501)', 'Fax: 37244500'],
        room: ['A.403'],
        star: false,
        website: 'law.uel.edu.vn',
      },
      {
        _id: 'dp0008',
        email: 'khoaluatkinhte@uel.edu.vn',
        logoUrl: 'dp0008.png',
        name: 'Khoa Luật Kinh tế',
        newsLink: 'https://lkt.uel.edu.vn/tin-tuc-7',
        notiLink: 'https://lkt.uel.edu.vn/chuyen-san-sinh-vien-phap-luat-2',
        page: 'https://www.facebook.com/',
        phone: ['(028) 3 37244555'],
        room: ['B2.404'],
        star: false,
        website: 'lkt.uel.edu.vn',
      },
      {
        _id: 'dp0009',
        email: 'khoaqtkd@uel.edu.vn',
        logoUrl: 'dp0009.png',
        name: 'Khoa Quản trị kinh doanh',
        newsLink: 'https://qtkd.uel.edu.vn/tin-tuc-48',
        notiLink: 'https://qtkd.uel.edu.vn/thong-bao2-62',
        page: 'https://www.facebook.com/',
        phone: ['(028) 37244555 (Ext 6461)', 'Fax: (028) 37244500'],
        room: ['B2.406'],
        star: false,
        website: 'qtkd.uel.edu.vn',
      },
      {
        _id: 'dp0010',
        email: 'khoatcnh@uel.edu.vn',
        logoUrl: 'dp0010.png',
        name: 'Khoa Tài chính ngân hàng',
        newsLink: 'https://fb.uel.edu.vn/doan-hoi',
        notiLink: 'https://fb.uel.edu.vn/thong-bao-khac',
        page: 'https://www.facebook.com/',
        phone: ['(028) 3 7244 555 (Ext 6481)', 'Fax: (028) 3 7244 500'],
        room: ['A.301'],
        star: false,
        website: 'fb.uel.edu.vn',
      },
      {
        _id: 'dp0011',
        email: 'khoaktkt@uel.edu.vn ',
        logoUrl: 'dp0011.png',
        name: 'Khoa Kế toán kiểm toán',
        newsLink: 'https://ktkt.uel.edu.vn/hoat-dong-khoa-1536',
        notiLink: 'https://ktkt.uel.edu.vn/thong-bao2-22',
        page: 'https://www.facebook.com/',
        phone: ['(08) 37244 555 (Ext 6471)'],
        room: ['A.308'],
        star: false,
        website: 'ktkt.uel.edu.vn',
      },
      {
        _id: 'dp0012',
        email: 'khoatkt@uel.edu.vn',
        logoUrl: 'dp0012.png',
        name: 'Khoa Toán Kinh tế',
        newsLink: 'https://maths.uel.edu.vn/thong-bao2-18',
        notiLink: 'https://maths.uel.edu.vn/thong-bao2-18',
        page: 'https://www.facebook.com/KhoatoanUEL',
        phone: ['(028) 3724 4555  (Ext 6601)'],
        room: ['A.206'],
        star: false,
        website: 'maths.uel.edu.vn',
      },
      {
        _id: 'dp0013',
        email: 'khoakt@uel.edu.vn',
        logoUrl: 'dp0013.png',
        name: 'Khoa Kinh tế',
        newsLink: 'https://maths.uel.edu.vn/thong-bao2-18',
        notiLink: 'https://kt.uel.edu.vn/seminar-khoa-hoc',
        page: 'https://www.facebook.com/',
        phone: ['(08) 3 7244 555 (Ext 6451)'],
        room: ['A.201'],
        star: false,
        website: 'kt.uel.edu.vn',
      },
      {
        _id: 'dp0014',
        email: 'phonghtpt@uel.edu.vn',
        logoUrl: 'dp0014.png',
        name: 'Phòng Hợp tác phát triển',
        newsLink: 'https://externalrelations.uel.edu.vn/thong-bao2-7',
        notiLink: 'https://externalrelations.uel.edu.vn/hoat-dong-682',
        page: 'https://www.facebook.com/',
        phone: ['(028) 37244555 (6361)'],
        room: ['A.108'],
        star: false,
        website: 'externalrelations.uel.edu.vn',
      },
    ];
  }

  url = "https://jsonplaceholder.typicode.com/todos";
}
